spring:
  application:
    name: BookingCreelHouse
  datasource:
    url: jdbc:h2:file:./booking.db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  ssl:
    bundle:
      pem:
        web:
          keystore:
            private-key: "base64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ2p2OUFSenJEM2o1VkZsclUKOTNyTm40NXNNN0VZYXpVQ0t5WWgrUHJGZXQraFJBTkNBQVExRnVQbURpREZERWxQTStZWjZCRXJGbUt3bXFzQgpteStOTUpXT3ZUOVJWSFZ1cHJjdXBpdlIyQnE2NC9NQzlmZ3B6Tnc5QVA1aUhNU2F5Z2syOGNtSAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNORENDQWRxZ0F3SUJBZ0lSQU9STDhBQktkOGM2a3lkdnJyS2Nremd3Q2dZSUtvWkl6ajBFQXdJd2ZURWUKTUJ3R0ExVUVDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQk1Ta3dKd1lEVlFRTERDQmhZbVJBWVdKawpMVlJvYVc1clVHRmtMVVV4TkMxSFpXNHROU0FvUVVKRUtURXdNQzRHQTFVRUF3d25iV3RqWlhKMElHRmlaRUJoClltUXRWR2hwYm10UVlXUXRSVEUwTFVkbGJpMDFJQ2hCUWtRcE1CNFhEVEkyTURReE5UQTNORFUwTkZvWERUSTQKTURjeE5UQTNORFUwTkZvd1ZERW5NQ1VHQTFVRUNoTWViV3RqWlhKMElHUmxkbVZzYjNCdFpXNTBJR05sY25ScApabWxqWVhSbE1Ta3dKd1lEVlFRTERDQmhZbVJBWVdKa0xWUm9hVzVyVUdGa0xVVXhOQzFIWlc0dE5TQW9RVUpFCktUQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJEVVc0K1lPSU1VTVNVOHo1aG5vRVNzV1lyQ2EKcXdHYkw0MHdsWTY5UDFGVWRXNm10eTZtSzlIWUdycmo4d0wxK0NuTTNEMEEvbUljeEpyS0NUYnh5WWVqWkRCaQpNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBVEFmQmdOVkhTTUVHREFXCmdCVHh0TGFTeWRpbDA1QWhIZWRqOEpxM3A3SnBaVEFhQmdOVkhSRUVFekFSZ2c5c2IyTmhiQzR3ZUdSaVpTNWsKWlhZd0NnWUlLb1pJemowRUF3SURTQUF3UlFJZ2IwSE1lUkFrUysvSzdHcVVUNE0zMVFsWnhUQ2l1emRKenBIRwo2eTVQTzFvQ0lRQ1VLRTI4T2x1cjNoZlIvNTFNekg0cXpwbzdjV1psOHhQK08yWm1UZHZUa3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
          truststore:
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNQakNDQWVTZ0F3SUJBZ0lSQUpOVElXUzRHbWlGMWJFVTMxT0Z0QW93Q2dZSUtvWkl6ajBFQXdJd2ZURWUKTUJ3R0ExVUVDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQk1Ta3dKd1lEVlFRTERDQmhZbVJBWVdKawpMVlJvYVc1clVHRmtMVVV4TkMxSFpXNHROU0FvUVVKRUtURXdNQzRHQTFVRUF3d25iV3RqWlhKMElHRmlaRUJoClltUXRWR2hwYm10UVlXUXRSVEUwTFVkbGJpMDFJQ2hCUWtRcE1CNFhEVEkyTURReE5UQTNORFF6TTFvWERUTTIKTURReE5UQTNORFF6TTFvd2ZURWVNQndHQTFVRUNoTVZiV3RqWlhKMElHUmxkbVZzYjNCdFpXNTBJRU5CTVNrdwpKd1lEVlFRTERDQmhZbVJBWVdKa0xWUm9hVzVyVUdGa0xVVXhOQzFIWlc0dE5TQW9RVUpFS1RFd01DNEdBMVVFCkF3d25iV3RqWlhKMElHRmlaRUJoWW1RdFZHaHBibXRRWVdRdFJURTBMVWRsYmkwMUlDaEJRa1FwTUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWcxNTR3UFJzR1JGNjE1QWlEZTZCUHlOaXZidmRzTHpNdHhkdQo4aWs3WndLRzl3MWxUcy8xdHNwRTFBZXJnVFZ2Rnl2RmFTVnN4M05VRGF2TkhOUnQ2S05GTUVNd0RnWURWUjBQCkFRSC9CQVFEQWdJRU1CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUVGUEcwdHBMSjJLWFQKa0NFZDUyUHdtcmVuc21sbE1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lCcEJ3TFJXS21QY3plenFuTXNQL0R2WAo3aXkzc2lUWllLdVVTWGw4c2xhUUFpRUFzZGZBYWh6eXhDRkwrSDZzeUpEM28rRHpPRWkxOE9wMHdlQ0lBdHVBClREWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="

server:
  port: 8443
  ssl:
    bundle: web
